export const data = [
  {
    type: "veg",
    id: "1",
    name: "Pizza",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
    rate: "4.5",
    time: "15-30 min",
    desc: " good pizza",
    adress: "nuhru nagar",
  },
  {
    type: "veg",
    id: "2",
    name: "Burger",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/508cd51f838c8f1899146f7ed69ef680",
    rate: "3.5",
    time: "15-30 min",
    desc: "By Mc Donald's",
    adress: "mumbai",
  },
  {
    type: "nonVeg",
    id: "3",
    name: "Biryani",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/86086acc172bc3b8efda352459cd11c8",
    rate: "4.8",
    time: "15-30 min",
    desc: "By Taj Darbar",
    adress: "belgavi",
  },
  {
    type: "nonVeg",
    id: "4",
    name: "Chicken Biryani",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/rmwotw5hyrqselw87jiy",
    rate: "3.5",
    time: "15-30 min",
    desc: "By Nandhana Palace",
    adress: "Belgaum",
  },
  {
    type: "nonVeg",
    id: "5",
    name: "Chicken Noodles",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/qmltqerhsoxv2fiiofvf",
    rate: "1.5",
    time: "15-30 min",
    desc: "good",
    adress: "nehru nagar",
  },
  {
    type: "nonVeg",
    id: "6",
    name: "pizza",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d0450ce1a6ba19ea60cd724471ed54a8",
    rate: "86.5",
    time: "15-30 min",
    desc: "Domino's",
    adress: "nehru nagar",
  },
  {
    type: "veg",
    id: "7",
    name: "dosa",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/4a752eab41d8483a070eb0b7840c7cc2",
    rate: "2.5",
    time: "15-30 min",
    desc: "Masala Dosa",
    adress: "nehru nagar",
  },
  {
    type: "veg",
    id: "8",
    name: "idli",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/lo7bzjsozelqke1zqstk",
    rate: "1.5",
    time: "15-30 min",
    desc: "Thatte Idli",
    adress: "nehru nagar",
  },
  {
    type: "veg",
    id: "9",
    name: "Pani Puri",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/14/fde0eee3-9aaa-421b-a12f-1cbd767c1aa4_53aadb67-c3f2-4d4b-b1b0-abd968f97f14.jpg",
    rate: "2.5",
    time: "15-30 min",
    desc: "Kalyani Sweets",
    adress: "camp",
  },
  {
    type: "veg",
    id: "10",
    name: "Momo's",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/gpojv1ofywjjpmxg9bmo",
    rate: "1.5",
    time: "15-30 min",
    desc: "Steam Momo",
    adress: "nehru nagar",
  },
  {
    type: "nonVeg",
    id: "11",
    name: "Shawarma",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/11/89e21492-9d2e-442b-b7db-af776c50846d_5dee07c7-8777-4764-ace4-1581b5c98bfc.png_compressed",
    rate: "1.5",
    time: "15-30 min",
    desc: "Peri Peri Shawarma",
    adress: "master chef's",
  },
  {
    type: "nonVeg",
    id: "12",
    name: "Seekh kebab",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/02dd46556e39a9dce8bd8a837f10e515",
    rate: "1.5",
    time: "15-30 min",
    desc: "seekh Darbar",
    adress: "subhas nagar",
  },
  {
    type: "veg",
    id: "13",
    name: "ice cream",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_264,h_288,c_fill/f20oitocgeivjijnanmi",
    rate: "1.5",
    time: "15-30 min",
    desc: "Naturals",
    adress: "nehru nagar",
  },
  {
    type: "veg",
    id: "14",
    name: "Shakes",
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_264,h_288,c_fill/a5b1713e5dbcac2d67a5bcb41e457ae3",
    rate: "1.5",
    time: "15-30 min",
    desc: "Frozen Bottle",
    adress: "nehru nagar",
  },
];
