export const data = [
  {
    type: "veg",
    id: "1",
    name: "Pizza",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    avgRatingString: "4.5",
    sla: "15-30 min",
    cuisines: " good pizza",
    areaName: "nuhru nagar",
  },
  {
    type: "veg",
    id: "2",
    name: "Burger",
    cloudinaryImageId: "508cd51f838c8f1899146f7ed69ef680",
    avgRatingString: "3.5",
    sla: "15-30 min",
    cuisines: "By Mc Donald's",
    areaName: "mumbai",
  },
  {
    type: "nonVeg",
    id: "3",
    name: "Biryani",
    cloudinaryImageId: "86086acc172bc3b8efda352459cd11c8",
    avgRatingString: "4.8",
    sla: "15-30 min",
    cuisines: "By Taj Darbar",
    areaName: "belgavi",
  },
  {
    type: "nonVeg",
    id: "4",
    name: "Chicken Biryani",
    cloudinaryImageId: "rmwotw5hyrqselw87jiy",
    avgRatingString: "3.5",
    sla: "15-30 min",
    cuisines: "By Nandhana Palace",
    areaName: "Belgaum",
  },
  {
    type: "nonVeg",
    id: "5",
    name: "Chicken Noodles",
    cloudinaryImageId: "qmltqerhsoxv2fiiofvf",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "good",
    areaName: "nehru nagar",
  },
  {
    type: "nonVeg",
    id: "6",
    name: "pizza",
    cloudinaryImageId: "d0450ce1a6ba19ea60cd724471ed54a8",
    avgRatingString: "86.5",
    sla: "15-30 min",
    cuisines: "Domino's",
    areaName: "nehru nagar",
  },
  {
    type: "veg",
    id: "7",
    name: "dosa",
    cloudinaryImageId: "4a752eab41d8483a070eb0b7840c7cc2",
    avgRatingString: "2.5",
    sla: "15-30 min",
    cuisines: "Masala Dosa",
    areaName: "nehru nagar",
  },
  {
    type: "veg",
    id: "8",
    name: "idli",
    cloudinaryImageId: "lo7bzjsozelqke1zqstk",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "Thatte Idli",
    areaName: "nehru nagar",
  },
  {
    type: "veg",
    id: "9",
    name: "Pani Puri",
    cloudinaryImageId:
      "FOOD_CATALOG/IMAGES/CMS/2024/3/14/fde0eee3-9aaa-421b-a12f-1cbd767c1aa4_53aadb67-c3f2-4d4b-b1b0-abd968f97f14.jpg",
    avgRatingString: "2.5",
    sla: "15-30 min",
    cuisines: "Kalyani Sweets",
    areaName: "camp",
  },
  {
    type: "veg",
    id: "10",
    name: "Momo's",
    cloudinaryImageId: "gpojv1ofywjjpmxg9bmo",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "Steam Momo",
    areaName: "nehru nagar",
  },
  {
    type: "nonVeg",
    id: "11",
    name: "Shawarma",
    cloudinaryImageId:
      "FOOD_CATALOG/IMAGES/CMS/2024/3/11/89e21492-9d2e-442b-b7db-af776c50846d_5dee07c7-8777-4764-ace4-1581b5c98bfc.png_compressed",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "Peri Peri Shawarma",
    areaName: "master chef's",
  },
  {
    type: "nonVeg",
    id: "12",
    name: "Seekh kebab",
    cloudinaryImageId: "02dd46556e39a9dce8bd8a837f10e515",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "seekh Darbar",
    areaName: "subhas nagar",
  },
  {
    type: "veg",
    id: "13",
    name: "ice cream",
    cloudinaryImageId: "f20oitocgeivjijnanmi",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "Naturals",
    areaName: "nehru nagar",
  },
  {
    type: "veg",
    id: "14",
    name: "Shakes",
    cloudinaryImageId: "a5b1713e5dbcac2d67a5bcb41e457ae3",
    avgRatingString: "1.5",
    sla: "15-30 min",
    cuisines: "Frozen Bottle",
    areaName: "nehru nagar",
  },
];
